"use client";

import { useState } from "react";
import { AlertTriangle, CalendarClock, CheckCircle2, ChevronLeft, ClipboardCheck, Gauge, MapPin, Plane, Settings2, ShieldCheck, Wrench } from "lucide-react";
import { Button } from "@/components/ui/button";
import { formatMoney } from "@/lib/game-data";
import type { FleetAction } from "@/lib/game/fleet-operations";
import type { AirlineState, CabinPreset, FleetAircraft } from "@/types/game";

export type FleetSection = "overview" | "register" | "induction" | "maintenance" | "acquisition";
type AircraftTab = "overview" | "cabin" | "maintenance" | "utilisation" | "assignment" | "contract" | "history";

const stages = ["technical", "registration", "cabin", "base"] as const;
const presets: { id: CabinPreset; label: string; description: string }[] = [
  { id: "high-density", label: "High-density low-cost", description: "Maximum seats and lowest unit cost." },
  { id: "standard", label: "Standard economy", description: "Balanced capacity and passenger comfort." },
  { id: "two-class", label: "Two-class regional", description: "Economy and business-class cabin." },
  { id: "three-class", label: "Three-class international", description: "Economy, premium economy and business." },
  { id: "premium", label: "Premium flagship", description: "Lower density with four cabin classes." },
];

function recordStatus(item: FleetAircraft) {
  if (item.status === "delivery") return "In delivery";
  if (item.status === "induction" || (item.inductionStage ?? "not-started") !== "complete") return "Induction required";
  if (item.status === "maintenance") return "In maintenance";
  if (item.status === "active") return "In service";
  return "Ready";
}

function AircraftWorkspace({ game, aircraft, onBack, onAction }: { game: AirlineState; aircraft: FleetAircraft; onBack: () => void; onAction: (aircraftId: string, action: FleetAction, option?: string) => void }) {
  const [tab, setTab] = useState<AircraftTab>("overview");
  const activeTask = game.fleetTasks.find((task) => task.aircraftId === aircraft.id && task.status === "active");
  const stage = aircraft.inductionStage ?? "not-started";
  const ready = stage === "complete" && aircraft.status !== "maintenance" && aircraft.status !== "delivery";

  return <div className="aircraft-workspace">
    <div className="manufacturer-showroom-nav"><button type="button" onClick={onBack}><ChevronLeft />Aircraft register</button><span>{aircraft.registration} · {aircraft.aircraft.model}</span></div>
    <header className="aircraft-workspace-hero"><div className="market-aircraft-icon"><Plane /></div><div><span>FLEET ASSET</span><h2>{aircraft.registration}</h2><p>{aircraft.aircraft.model} · {aircraft.manufactureYear} · {aircraft.acquisitionType}</p></div><div className={`readiness-badge ${ready ? "ready" : "attention"}`}>{ready ? <CheckCircle2 /> : <AlertTriangle />}{ready ? "Operationally ready" : recordStatus(aircraft)}</div></header>
    <div className="aircraft-workspace-tabs">{(["overview", "cabin", "maintenance", "utilisation", "assignment", "contract", "history"] as AircraftTab[]).map((item) => <button key={item} type="button" className={tab === item ? "active" : ""} onClick={() => setTab(item)}>{item}</button>)}</div>

    {activeTask && <div className="active-work-banner"><CalendarClock /><div><strong>{activeTask.label}</strong><span>{activeTask.provider} · completes {new Date(activeTask.completesAt).toLocaleString("en-ZA", { timeZone: "UTC" })}</span></div></div>}
    {tab === "overview" && <div className="fleet-detail-grid"><article><span>AIRCRAFT RECORD</span><dl><div><dt>Serial number</dt><dd>{aircraft.serialNumber ?? aircraft.id.slice(-10).toUpperCase()}</dd></div><div><dt>Current location</dt><dd>{aircraft.currentLocation ?? game.hub.code}</dd></div><div><dt>Assigned base</dt><dd>{aircraft.baseCode ?? "Not assigned"}</dd></div><div><dt>Status</dt><dd>{recordStatus(aircraft)}</dd></div><div><dt>Flight hours</dt><dd>{aircraft.flightHours.toLocaleString()}</dd></div><div><dt>Flight cycles</dt><dd>{(aircraft.flightCycles ?? 0).toLocaleString()}</dd></div></dl></article><article><span>READINESS CHECKLIST</span><div className="readiness-list"><p className={stage !== "not-started" ? "done" : ""}><ClipboardCheck />Technical acceptance</p><p className={aircraft.locallyRegistered ? "done" : ""}><ShieldCheck />Registration completed</p><p className={aircraft.insured ? "done" : ""}><ShieldCheck />Insurance active</p><p className={aircraft.cabinClasses ? "done" : ""}><Settings2 />Cabin configured</p><p className={aircraft.baseCode ? "done" : ""}><MapPin />Base assigned</p><p className={ready ? "done" : ""}><CheckCircle2 />Operational release</p></div></article></div>}
    {tab === "cabin" && <article className="workspace-panel"><div className="workspace-heading"><div><span>CABIN CONFIGURATION</span><h3>{aircraft.cabinPreset ? presets.find((item) => item.id === aircraft.cabinPreset)?.label : "No cabin selected"}</h3></div></div>{aircraft.cabinClasses && <div className="cabin-summary"><div><span>ECONOMY</span><strong>{aircraft.cabinClasses.economy}</strong></div><div><span>PREMIUM ECONOMY</span><strong>{aircraft.cabinClasses.premiumEconomy}</strong></div><div><span>BUSINESS</span><strong>{aircraft.cabinClasses.business}</strong></div><div><span>FIRST</span><strong>{aircraft.cabinClasses.first}</strong></div></div>}<div className="cabin-preset-grid">{presets.map((preset) => <button type="button" key={preset.id} className={aircraft.cabinPreset === preset.id ? "selected" : ""} disabled={Boolean(activeTask) || stage !== "registration"} onClick={() => onAction(aircraft.id, "configure-cabin", preset.id)}><strong>{preset.label}</strong><span>{preset.description}</span></button>)}</div>{stage !== "registration" && !aircraft.cabinClasses && <small>Complete registration and insurance before beginning cabin work.</small>}</article>}
    {tab === "maintenance" && <article className="workspace-panel"><div className="workspace-heading"><div><span>TECHNICAL MANAGEMENT</span><h3>Condition {aircraft.condition.toFixed(1)}%</h3></div><small>Next scheduled event: {aircraft.nextMaintenanceAt ? new Date(aircraft.nextMaintenanceAt).toLocaleDateString("en-ZA", { timeZone: "UTC" }) : "Not scheduled"}</small></div><div className="maintenance-actions"><button disabled={Boolean(activeTask) || !ready} onClick={() => onAction(aircraft.id, "line-maintenance")}><Wrench /><strong>Line maintenance</strong><span>1 day · {formatMoney(280_000)}</span></button><button disabled={Boolean(activeTask) || !ready} onClick={() => onAction(aircraft.id, "a-check")}><Wrench /><strong>Scheduled A-check</strong><span>2 days · {formatMoney(1_450_000)}</span></button><button disabled={Boolean(activeTask) || !ready} onClick={() => onAction(aircraft.id, "c-check")}><Wrench /><strong>Heavy C-check</strong><span>14 days · {formatMoney(8_900_000)}</span></button></div></article>}
    {tab === "utilisation" && <article className="workspace-panel"><div className="workspace-heading"><div><span>UTILISATION</span><h3>Aircraft activity</h3></div></div><div className="cabin-summary"><div><span>WEEKLY HOURS</span><strong>{aircraft.status === "active" ? "42.6" : "0.0"}</strong></div><div><span>SECTORS</span><strong>{aircraft.status === "active" ? "28" : "0"}</strong></div><div><span>UTILISATION</span><strong>{aircraft.status === "active" ? "67%" : "0%"}</strong></div><div><span>GROUND TIME</span><strong>{aircraft.status === "active" ? "33%" : "100%"}</strong></div></div><p className="workspace-note">Detailed schedule and profit contribution will activate when this aircraft is assigned through the route-planning system.</p></article>}
    {tab === "assignment" && <article className="workspace-panel"><div className="workspace-heading"><div><span>BASE & ROUTE ASSIGNMENT</span><h3>{aircraft.baseCode ?? "No base assigned"}</h3></div></div><div className="assignment-state"><MapPin /><div><strong>{aircraft.baseCode ? `${aircraft.baseCode} operating base` : "Base assignment pending"}</strong><span>{ready ? "Aircraft is ready for route planning." : "Complete induction before assigning the aircraft to commercial services."}</span></div></div></article>}
    {tab === "contract" && <article className="workspace-panel"><div className="workspace-heading"><div><span>CONTRACT & FINANCE</span><h3>{aircraft.acquisitionType === "owned" ? "Owned aircraft" : aircraft.acquisitionType === "leased" ? "Operating lease" : "Aircraft finance"}</h3></div></div><div className="history-metrics"><div><span>PROVIDER</span><strong>{aircraft.provider}</strong></div><div><span>ACQUISITION VALUE</span><strong>{formatMoney(aircraft.purchasePrice)}</strong></div><div><span>MONTHLY COMMITMENT</span><strong>{formatMoney(aircraft.monthlyPayment)}</strong></div><div><span>OUTSTANDING BALANCE</span><strong>{formatMoney(aircraft.outstandingBalance)}</strong></div></div></article>}
    {tab === "history" && <article className="workspace-panel"><div className="workspace-heading"><div><span>AIRCRAFT HISTORY</span><h3>Permanent fleet record</h3></div></div><div className="aircraft-history"><div><i /><span><strong>Aircraft acquired</strong><small>{new Date(aircraft.acquiredAt).toLocaleString("en-ZA", { timeZone: "UTC" })} · {aircraft.provider}</small></span></div>{game.fleetTasks.filter((task) => task.aircraftId === aircraft.id).map((task) => <div key={task.id}><i /><span><strong>{task.label}</strong><small>{task.status} · {task.provider} · {formatMoney(task.cost)}</small></span></div>)}</div></article>}
  </div>;
}

export function FleetManagement({ game, section, onAction }: { game: AirlineState; section: Exclude<FleetSection, "acquisition">; onAction: (aircraftId: string, action: FleetAction, option?: string) => void }) {
  const [selectedId, setSelectedId] = useState<string | null>(null);
  const selected = game.fleet.find((item) => item.id === selectedId);
  if (selected) return <AircraftWorkspace game={game} aircraft={selected} onBack={() => setSelectedId(null)} onAction={onAction} />;
  const ready = game.fleet.filter((item) => (item.inductionStage ?? "not-started") === "complete" && item.status === "parked").length;
  const induction = game.fleet.filter((item) => item.status === "induction" || ((item.inductionStage ?? "not-started") !== "complete" && item.status !== "delivery")).length;
  const maintenance = game.fleet.filter((item) => item.status === "maintenance").length;
  const delivery = game.fleet.filter((item) => item.status === "delivery").length;

  if (game.fleet.length === 0) return <div className="fleet-empty-workspace"><Plane /><h2>No aircraft in the fleet</h2><p>Acquire an aircraft first, then return here to manage induction and operational readiness.</p></div>;
  if (section === "overview") return <div className="fleet-operations-overview"><div className="fleet-ownership-summary"><article><span>TOTAL FLEET</span><strong>{game.fleet.length}</strong></article><article><span>READY</span><strong>{ready}</strong></article><article><span>IN DELIVERY</span><strong>{delivery}</strong></article><article><span>INDUCTION</span><strong>{induction}</strong></article><article><span>MAINTENANCE</span><strong>{maintenance}</strong></article><article><span>AVG. CONDITION</span><strong>{(game.fleet.reduce((sum, item) => sum + item.condition, 0) / game.fleet.length).toFixed(1)}%</strong></article></div><div className="fleet-attention panel"><div className="panel-heading compact"><div><span className="panel-eyebrow">FLEET CONTROL</span><h2>Aircraft requiring attention</h2></div></div>{game.fleet.filter((item) => recordStatus(item) !== "Ready" && recordStatus(item) !== "In service").map((item) => <button type="button" key={item.id} onClick={() => setSelectedId(item.id)}><span><Plane /><strong>{item.registration}</strong>{item.aircraft.model}</span><em>{recordStatus(item)}</em></button>)}</div></div>;
  if (section === "induction") return <div className="induction-board">{game.fleet.filter((item) => (item.inductionStage ?? "not-started") !== "complete").map((item) => { const current = item.inductionStage ?? "not-started"; const task = game.fleetTasks.find((entry) => entry.aircraftId === item.id && entry.status === "active"); return <article key={item.id}><header><div><span>{item.registration}</span><h3>{item.aircraft.model}</h3></div><em>{task ? "Work in progress" : "Action required"}</em></header><div className="induction-timeline">{stages.map((stageName) => { const currentIndex = stages.indexOf(current as typeof stages[number]); const index = stages.indexOf(stageName); return <div className={current === "complete" || index <= currentIndex ? "done" : index === currentIndex + 1 ? "next" : ""} key={stageName}><i />{stageName}</div>; })}</div>{task ? <p>{task.label}<small>Completes {new Date(task.completesAt).toLocaleString("en-ZA", { timeZone: "UTC" })}</small></p> : current === "registration" ? <Button onClick={() => setSelectedId(item.id)}>Configure cabin</Button> : <Button onClick={() => onAction(item.id, "advance-induction")}>{current === "not-started" ? "Begin induction" : "Start next stage"}</Button>}</article>; })}</div>;
  if (section === "maintenance") return <div className="maintenance-control"><div className="fleet-attention panel">{game.fleet.map((item) => <button type="button" key={item.id} onClick={() => setSelectedId(item.id)}><span><Gauge /><strong>{item.registration}</strong>{item.condition.toFixed(1)}% condition</span><em>{item.status === "maintenance" ? "In maintenance" : item.nextMaintenanceAt ? new Date(item.nextMaintenanceAt).toLocaleDateString("en-ZA", { timeZone: "UTC" }) : "Induction pending"}</em></button>)}</div></div>;
  return <div className="aircraft-register-table-wrap"><table className="aircraft-register-table"><thead><tr><th>Aircraft</th><th>Ownership</th><th>Location/base</th><th>Hours/cycles</th><th>Condition</th><th>Status</th><th /></tr></thead><tbody>{game.fleet.map((item) => <tr key={item.id}><td><strong>{item.registration}</strong><small>{item.aircraft.model} · {item.manufactureYear}</small></td><td>{item.acquisitionType}</td><td><strong>{item.currentLocation ?? game.hub.code}</strong><small>Base: {item.baseCode ?? "Not assigned"}</small></td><td>{item.flightHours.toLocaleString()}<small>{(item.flightCycles ?? 0).toLocaleString()} cycles</small></td><td>{item.condition.toFixed(1)}%</td><td><span className="register-status">{recordStatus(item)}</span></td><td><Button size="sm" variant="outline" onClick={() => setSelectedId(item.id)}>Manage</Button></td></tr>)}</tbody></table></div>;
}
